# Generated by Django 3.2 on 2022-09-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='total_item',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
