# Generated by Django 3.2 on 2022-09-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitems_isorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='quatntity',
            new_name='quantity',
        ),
    ]
