# Generated by Django 3.2 on 2022-09-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
