# Generated by Django 3.2 on 2022-09-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220922_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='price',
            field=models.ForeignKey(default=150000, on_delete=django.db.models.deletion.CASCADE, related_name='payed_price', to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_course', to='course.course'),
        ),
    ]
