# Generated by Django 3.2 on 2022-09-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220923_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='price',
        ),
    ]
