# Generated by Django 3.2 on 2022-09-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_registereduser_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='course',
            new_name='price',
        ),
    ]
