# Generated by Django 3.2 on 2022-09-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_course_registereduser_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='price',
            new_name='category',
        ),
    ]
