# Generated by Django 3.2 on 2022-09-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_price_registereduser_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='category',
            new_name='course',
        ),
    ]
