# Generated by Django 3.2 on 2022-09-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename_category_registereduser_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
