# Generated by Django 3.2 on 2022-10-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='aa', max_length=500),
            preserve_default=False,
        ),
    ]
